### ISSUE TITLE
I am getting "connect ECONNREFUSED 127.0.0.1:4444" after running npm test. I also verified that 127.0.0.1:4444 is not being used in machine

### ISSUE THREAD

**Issue by sachin-s-joshi** [rodrigovolkmer/cucumber-wdioFramework#2]
Here is the log:
Stdout:
2019-01-28T12:21:12.115Z INFO wdio-cli:Launcher: Run onPrepare hook
2019-01-28T12:21:12.118Z INFO wdio-local-runner: Start worker 0-0 with arg: wdio.conf.js
2019-01-28T12:21:16.903Z DEBUG wdio-local-runner: Runner 0-0 finished with exit code 1
2019-01-28T12:21:16.907Z INFO wdio-local-runner: Start worker 0-1 with arg: wdio.conf.js
2019-01-28T12:21:21.726Z DEBUG wdio-local-runner: Runner 0-1 finished with exit code 1
2019-01-28T12:21:21.730Z INFO wdio-cli:Launcher: Run onComplete hook

Worker Error:
Error: connect ECONNREFUSED 127.0.0.1:4444
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
Error: connect ECONNREFUSED 127.0.0.1:4444
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

**Comment by sachin-s-joshi** [comment]
Resolved. I deleted node_modules and re-installed again and the issue didn't occur.
